### ISSUE TITLE
Issue with Installing TRACE software

### ISSUE THREAD

**Issue by solaire678** [ilwoolyu/CurveExtraction#1]
Dear experts,

First of all, I would like to thank you for this excellent software. It is truly interesting and offers great functionality. I am excited to work with it but am currently facing some difficulties during installation. I could succesfully build and compile the MeshLib package, however while configuring the TRACE project with CMake, I am encountering the following error:

> CMake Error at CMakeLists.txt:23 (find_package):
>   By not providing "FindMeshLib.cmake" in CMAKE_MODULE_PATH this project has
>   asked CMake to find a package configuration file provided by "MeshLib", but
>   CMake did not find one.
> 
>   Could not find a package configuration file provided by "MeshLib" with any
>   of the following names:
> 
>     MeshLibConfig.cmake
>     meshlib-config.cmake
> 
>   Add the installation prefix of "MeshLib" to CMAKE_PREFIX_PATH or set
>   "MeshLib_DIR" to a directory containing one of the above files.  If
>   "MeshLib" provides a separate development package or SDK, be sure it has
>   been installed.

I would greatly appreciate any guidance or suggestions on how to resolve this issue.
Thank you once again and I look forward to your help!

Best regards,
Cris

**Comment by ilwoolyu** [comment]
Hi Cris,

Thank you for your interest in my software. Once MeshLib is successfully compiled, you should be able to see the `MeshLibConfig.cmake` file in the compiled directory. In ccmake, you can specify the path to `MeshLib_DIR` for TRACE and press `c` to configure. Let me know if you have any questions.

Best,
Ilwoo

**Comment by solaire678** [comment]
Dear Ilwoo,

It works now, thank you for your help :)

Best,

Cris
